import React, { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import Header from "../components/Header";
import Footer from "../components/Footer";
import javaLogo from "../assets/Java-Logo.png";
import pythonLogo from "../assets/python logo.jpeg";
import javaFullStack from "../assets/java-fullstack.jpg";
import pythonFullStack from "../assets/python full stack.jpeg";
import mernStack from "../assets/mernstack.jpeg";
import dataAnalytics from "../assets/data analytics.jpeg";
import genaiLogo from "../assets/genai logo.png";
import devopsLogo from "../assets/devops.png";
import javaSqlLogo from "../assets/java with sql combo.png";
const courses = [
  {
  title: "Java Development",

  image: javaLogo,

  category: "Programming",

  level: "Beginner",

  duration: "45 Days",

  mode: "Online Live",

  badge: "Popular",

  description:
    "Master Java programming from fundamentals to advanced concepts through practical coding, projects, DSA, JDBC, testing, and interview preparation.",

  topics: [
    "Java Introduction & JVM",
    "Java Fundamentals",
    "Variables & Data Types",
    "Operators & Type Casting",
    "Control Statements",
    "Arrays",
    "Strings",
    "Methods",
    "Classes & Objects",
    "Encapsulation",
    "Inheritance",
    "Polymorphism",
    "Abstraction",
    "Interfaces",
    "Packages & Access Modifiers",
    "Exception Handling",
    "Wrapper Classes & Enums",
    "Collections Framework",
    "Generics",
    "Lambda Expressions",
    "Stream API",
    "Optional & Date-Time API",
    "File Handling & I/O",
    "Multithreading & Concurrency",
    "JDBC & Database Connectivity",
    "JVM & Memory Management",
    "Testing & Debugging",
    "Design Principles & Patterns",
    "DSA with Java",
    "Projects & Interview Preparation",
  ],

  modules: [
    {
      name: "Module 1 - Introduction to Java",
      topics: [
        "Introduction to Java",
        "History & Evolution of Java",
        "Features of Java",
        "Java Applications",
        "Java Editions",
        "JDK",
        "JRE",
        "JVM",
        "JDK vs JRE vs JVM",
        "JVM Architecture",
        "Bytecode",
        "Java Compilation & Execution",
        "Java Installation",
        "IDE Setup",
        "First Java Program",
      ],
    },

    {
      name: "Module 2 - Java Fundamentals",
      topics: [
        "Java Syntax",
        "Java Program Structure",
        "Keywords",
        "Identifiers",
        "Variables",
        "Constants",
        "Primitive Data Types",
        "Reference Data Types",
        "Literals",
        "Comments",
        "Variable Scope",
        "Variable Lifetime",
        "Naming Conventions",
      ],
    },

    {
      name: "Module 3 - Operators & Type Conversion",
      topics: [
        "Arithmetic Operators",
        "Unary Operators",
        "Assignment Operators",
        "Relational Operators",
        "Logical Operators",
        "Ternary Operator",
        "Bitwise Operators",
        "Shift Operators",
        "Operator Precedence",
        "Operator Associativity",
        "Type Casting",
        "Widening",
        "Narrowing",
        "Implicit Conversion",
        "Explicit Conversion",
      ],
    },

    {
      name: "Module 4 - Input, Output & Control Statements",
      topics: [
        "Scanner",
        "BufferedReader",
        "Command-Line Arguments",
        "System.out",
        "print()",
        "println()",
        "printf()",
        "if Statement",
        "if-else",
        "else-if",
        "Nested if",
        "switch Statement",
        "Switch Expressions",
        "for Loop",
        "while Loop",
        "do-while Loop",
        "Nested Loops",
        "break",
        "continue",
        "return",
      ],
    },

    {
      name: "Module 5 - Arrays",
      topics: [
        "Array Fundamentals",
        "Array Declaration",
        "Array Initialization",
        "One-Dimensional Arrays",
        "Two-Dimensional Arrays",
        "Multidimensional Arrays",
        "Jagged Arrays",
        "Array of Objects",
        "Array Traversal",
        "Searching Arrays",
        "Sorting Arrays",
        "Copying Arrays",
        "Comparing Arrays",
        "Arrays Utility Class",
        "Common Array Programs",
      ],
    },

    {
      name: "Module 6 - Strings",
      topics: [
        "String Introduction",
        "String Creation",
        "String Literals",
        "String Pool",
        "String Immutability",
        "String Comparison",
        "String Methods",
        "String Searching",
        "String Manipulation",
        "substring()",
        "indexOf()",
        "replace()",
        "split()",
        "trim()",
        "StringBuilder",
        "StringBuffer",
        "String vs StringBuilder vs StringBuffer",
        "String Practice Programs",
      ],
    },

    {
      name: "Module 7 - Methods",
      topics: [
        "Method Introduction",
        "Method Declaration",
        "Method Definition",
        "Method Calling",
        "Parameters",
        "Arguments",
        "Return Types",
        "Void Methods",
        "Static Methods",
        "Instance Methods",
        "Method Overloading",
        "Varargs",
        "Recursion",
        "Pass-by-Value",
        "Method Scope",
        "Method-Based Programs",
      ],
    },

    {
      name: "Module 8 - Classes & Objects",
      topics: [
        "Object-Oriented Programming Introduction",
        "Classes",
        "Objects",
        "Fields",
        "Instance Variables",
        "Instance Methods",
        "Object Creation",
        "Constructors",
        "Default Constructor",
        "Parameterized Constructor",
        "Constructor Overloading",
        "Constructor Chaining",
        "this Keyword",
        "Object References",
      ],
    },

    {
      name: "Module 9 - Encapsulation & Inheritance",
      topics: [
        "Encapsulation",
        "Data Hiding",
        "Getters & Setters",
        "Access Control",
        "Inheritance",
        "extends Keyword",
        "Parent & Child Classes",
        "Single Inheritance",
        "Multilevel Inheritance",
        "Hierarchical Inheritance",
        "super Keyword",
        "Constructor Chaining",
        "IS-A Relationship",
        "HAS-A Relationship",
        "Composition",
        "Aggregation",
      ],
    },

    {
      name: "Module 10 - Polymorphism & Abstraction",
      topics: [
        "Polymorphism",
        "Compile-Time Polymorphism",
        "Method Overloading",
        "Runtime Polymorphism",
        "Method Overriding",
        "Dynamic Method Dispatch",
        "Upcasting",
        "Downcasting",
        "Abstraction",
        "Abstract Classes",
        "Abstract Methods",
        "Interfaces",
        "Implementing Interfaces",
        "Multiple Interfaces",
        "Default Interface Methods",
        "Static Interface Methods",
        "Abstract Class vs Interface",
      ],
    },

    {
      name: "Module 11 - Packages, Access Modifiers & Object Class",
      topics: [
        "Packages",
        "Built-in Packages",
        "User-Defined Packages",
        "import Statement",
        "Static Import",
        "public",
        "private",
        "protected",
        "default Access",
        "Object Class",
        "toString()",
        "equals()",
        "hashCode()",
        "getClass()",
        "instanceof",
      ],
    },

    {
      name: "Module 12 - Exception Handling",
      topics: [
        "Exception Introduction",
        "Error vs Exception",
        "Exception Hierarchy",
        "Checked Exceptions",
        "Unchecked Exceptions",
        "try Block",
        "catch Block",
        "finally Block",
        "Multiple catch",
        "Nested try",
        "throw",
        "throws",
        "Exception Propagation",
        "Custom Exceptions",
        "User-Defined Exceptions",
        "Try-with-Resources",
        "Common Java Exceptions",
      ],
    },

    {
      name: "Module 13 - Wrapper Classes, Enum & Annotations",
      topics: [
        "Wrapper Classes",
        "Integer",
        "Double",
        "Float",
        "Long",
        "Character",
        "Boolean",
        "Autoboxing",
        "Unboxing",
        "Parsing",
        "Enum",
        "Enum Constants",
        "Enum Methods",
        "Enum with switch",
        "EnumSet",
        "EnumMap",
        "Annotations",
        "Built-in Annotations",
        "Custom Annotations Basics",
      ],
    },

    {
      name: "Module 14 - Collection Framework",
      topics: [
        "Collection Framework Introduction",
        "Iterable",
        "Collection Interface",
        "List",
        "Set",
        "Queue",
        "Deque",
        "Map",
        "Collection Hierarchy",
        "ArrayList",
        "LinkedList",
        "Vector",
        "Stack",
        "HashSet",
        "LinkedHashSet",
        "TreeSet",
        "PriorityQueue",
        "ArrayDeque",
      ],
    },

    {
      name: "Module 15 - Map, Iterator & Sorting",
      topics: [
        "HashMap",
        "LinkedHashMap",
        "TreeMap",
        "Hashtable",
        "ConcurrentHashMap Basics",
        "Iterator",
        "ListIterator",
        "Enhanced for Loop",
        "Comparable",
        "compareTo()",
        "Comparator",
        "compare()",
        "Natural Ordering",
        "Custom Sorting",
        "Collections Utility Class",
        "Fail-Fast Concept",
        "Collection Practice Programs",
      ],
    },

    {
      name: "Module 16 - Generics",
      topics: [
        "Generic Programming",
        "Generic Classes",
        "Generic Methods",
        "Generic Interfaces",
        "Type Parameters",
        "Generic Collections",
        "Bounded Types",
        "Upper Bounds",
        "Lower Bounds",
        "Wildcards",
        "Unbounded Wildcards",
        "Type Safety",
        "Type Erasure Basics",
      ],
    },

    {
      name: "Module 17 - Lambda & Functional Interfaces",
      topics: [
        "Functional Programming",
        "Lambda Expressions",
        "Lambda Syntax",
        "Functional Interfaces",
        "Predicate",
        "Consumer",
        "Supplier",
        "Function",
        "UnaryOperator",
        "BinaryOperator",
        "BiPredicate",
        "BiConsumer",
        "BiFunction",
        "Method References",
        "Constructor References",
        "@FunctionalInterface",
      ],
    },

    {
      name: "Module 18 - Stream API",
      topics: [
        "Stream API Introduction",
        "Stream Creation",
        "Stream vs Collection",
        "Intermediate Operations",
        "Terminal Operations",
        "filter()",
        "map()",
        "flatMap()",
        "sorted()",
        "distinct()",
        "limit()",
        "skip()",
        "forEach()",
        "collect()",
        "reduce()",
        "count()",
        "min()",
        "max()",
        "findFirst()",
        "findAny()",
         ],
    },

    {
      name: "Module 19 - Optional & Date-Time API",
      topics: [
        "Null Handling",
        "Optional",
        "Optional.of()",
        "Optional.ofNullable()",
        "Optional.empty()",
        "isPresent()",
        "isEmpty()",
        "ifPresent()",
        "orElse()",
        "orElseGet()",
        "orElseThrow()",
        "LocalDate",
        "LocalTime",
        "LocalDateTime",
        "ZonedDateTime",
        "Period",
        "Duration",
        "Date Formatting",
        "Date Parsing",
        "Time Zones",
      ],
    },

    {
      name: "Module 20 - File Handling & I/O",
      topics: [
        "File Handling",
        "File Class",
        "Creating Files",
        "Reading Files",
        "Writing Files",
        "Copying Files",
        "Moving Files",
        "Deleting Files",
        "Directory Handling",
        "InputStream",
        "OutputStream",
        "FileInputStream",
        "FileOutputStream",
        "Reader",
        "Writer",
        "FileReader",
        "FileWriter",
        "BufferedReader",
        "BufferedWriter",
        "Java NIO Basics",
        "Path",
        "Files",
      ],
    },

    {
      name: "Module 21 - Serialization, Inner Classes & Reflection",
      topics: [
        "Serialization",
        "Deserialization",
        "Serializable",
        "serialVersionUID",
        "transient Keyword",
        "ObjectOutputStream",
        "ObjectInputStream",
        "Inner Classes",
        "Static Nested Classes",
        "Local Inner Classes",
        "Anonymous Inner Classes",
        "Reflection Introduction",
        "Class Object",
        "Reflection Fields",
        "Reflection Methods",
        "Reflection Constructors",
      ],
    },

    {
      name: "Module 22 - Multithreading & Concurrency",
      topics: [
        "Process vs Thread",
        "Thread Introduction",
        "Thread Lifecycle",
        "Thread Class",
        "Runnable",
        "Callable",
        "Thread Methods",
        "start()",
        "run()",
        "sleep()",
        "join()",
        "interrupt()",
        "Daemon Threads",
        "Thread Priority",
        "Synchronization",
        "Synchronized Methods",
        "Synchronized Blocks",
        "Race Conditions",
        "Deadlock",
        "wait()",
        "notify()",
        "notifyAll()",
      ],
    },
    {
      name: "Module 23 - Projects & Interview Preparation",
      topics: [
        "Real-Time Application",
        "Final Project",
        "Core Java Interview Questions",
        "OOP Interview Questions",
        "Collections Interview Questions",
        "Exception Handling Questions",
        "Multithreading Questions",
        "Coding Interview Questions",
        "Output-Based Questions",
        "Debugging Questions",
        "Mock Technical Interview",
        "Project Explanation",
        "HR Interview Preparation",
      ],
    },
  ],
},
  {
  title: "Python Programming",
  category: "Programming",
  image: pythonLogo,
  level: "Beginner to Advanced",

  duration: "2 Months",

  mode: "Online Live",

  badge: "Popular",

  description:
    "Learn Python programming from fundamentals to advanced concepts with practical coding, OOP, file handling, databases, APIs, projects, and interview preparation.",

  topics: [
    "Python Fundamentals",
    "Variables & Data Types",
    "Operators",
    "Input & Output",
    "Control Statements",
    "Loops",
    "Functions",
    "Recursion",
    "Lists",
    "Tuples",
    "Sets",
    "Dictionaries",
    "Strings",
    "List Comprehensions",
    "Modules & Packages",
    "Exception Handling",
    "File Handling",
    "Object-Oriented Programming",
    "Inheritance & Polymorphism",
    "Lambda Functions",
    "Functional Programming",
    "Regular Expressions",
    "Date & Time",
    "Virtual Environments",
    "Data Structures & Algorithms",
    "Python Coding Practice",
    "Mini Projects",
    "Final Project",
    "Interview Preparation",
  ],

  modules: [
    {
      name: "Module 1 - Introduction to Python",
      topics: [
        "Introduction to Python",
        "History of Python",
        "Features of Python",
        "Applications of Python",
        "Python Versions",
        "Python Installation",
        "Python Interpreter",
        "Python IDEs",
        "VS Code",
        "PyCharm",
        "Python Program Structure",
        "First Python Program",
        "Python Coding Standards",
      ],
    },

    {
      name: "Module 2 - Python Fundamentals",
      topics: [
        "Python Syntax",
        "Keywords",
        "Identifiers",
        "Variables",
        "Constants",
        "Comments",
        "Dynamic Typing",
        "Variable Naming",
        "Data Types",
        "Type Checking",
        "Type Conversion",
        "Type Casting",
        "Mutable and Immutable Objects",
      ],
    },

    {
      name: "Module 3 - Operators & Input Output",
      topics: [
        "Arithmetic Operators",
        "Assignment Operators",
        "Comparison Operators",
        "Logical Operators",
        "Identity Operators",
        "Membership Operators",
        "Bitwise Operators",
        "Operator Precedence",
        "input()",
        "print()",
        "Formatted Output",
        "f-Strings",
        "String Formatting",
      ],
    },

    {
      name: "Module 4 - Conditional Statements",
      topics: [
        "if Statement",
        "if-else",
        "elif",
        "Nested Conditions",
        "Conditional Expressions",
        "Multiple Conditions",
        "Truth Values",
        "Truthy and Falsy Values",
        "Practical Conditional Programs",
      ],
    },

    {
      name: "Module 5 - Loops & Control Flow",
      topics: [
        "for Loop",
        "while Loop",
        "Nested Loops",
        "range()",
        "break",
        "continue",
        "pass",
        "Loop else",
        "Enumerate",
        "Zip",
        "Pattern Programs",
        "Number Programs",
      ],
    },

    {
      name: "Module 6 - Strings",
      topics: [
        "String Fundamentals",
        "String Creation",
        "String Indexing",
        "String Slicing",
        "String Methods",
        "upper()",
        "lower()",
        "strip()",
        "replace()",
        "split()",
        "join()",
        "find()",
        "count()",
        "startswith()",
        "endswith()",
        "String Formatting",
        "String Practice Programs",
      ],
    },

    {
      name: "Module 7 - Lists",
      topics: [
        "List Introduction",
        "Creating Lists",
        "List Indexing",
        "List Slicing",
        "List Methods",
        "append()",
        "extend()",
        "insert()",
        "remove()",
        "pop()",
        "sort()",
        "reverse()",
        "copy()",
        "Nested Lists",
        "List of Objects",
        "List Comprehensions",
        "List Practice Programs",
      ],
    },

    {
      name: "Module 8 - Tuples, Sets & Dictionaries",
      topics: [
        "Tuples",
        "Tuple Operations",
        "Tuple Methods",
        "Sets",
        "Set Operations",
        "Union",
        "Intersection",
        "Difference",
        "Symmetric Difference",
        "Set Methods",
        "Dictionaries",
        "Dictionary Keys & Values",
        "Dictionary Methods",
        "Nested Dictionaries",
        "Dictionary Comprehensions",
        "Practical Collection Programs",
      ],
    },

    {
      name: "Module 9 - Functions",
      topics: [
        "Function Introduction",
        "Defining Functions",
        "Calling Functions",
        "Parameters",
        "Arguments",
        "Return Values",
        "Default Arguments",
        "Keyword Arguments",
        "Positional Arguments",
        "Variable-Length Arguments",
        "*args",
        "**kwargs",
        "Scope of Variables",
        "Local Variables",
        "Global Variables",
        "Nonlocal Variables",
        "Docstrings",
      ],
    },

    {
      name: "Module 10 - Recursion & Lambda",
      topics: [
        "Recursion",
        "Recursive Functions",
        "Base Condition",
        "Factorial Using Recursion",
        "Fibonacci Using Recursion",
        "Lambda Functions",
        "Lambda Syntax",
        "Lambda with Lists",
        "Lambda with sorted()",
        "Lambda with filter()",
        "Lambda with map()",
        "Lambda with reduce()",
      ],
    },

    {
      name: "Module 11 - Comprehensions & Functional Programming",
      topics: [
        "List Comprehensions",
        "Set Comprehensions",
        "Dictionary Comprehensions",
        "Nested Comprehensions",
        "map()",
        "filter()",
        "reduce()",
        "zip()",
        "enumerate()",
        "any()",
        "all()",
        "sorted()",
        "Functional Programming Basics",
      ],
    },

    {
      name: "Module 12 - Modules & Packages",
      topics: [
        "Modules",
        "Creating Modules",
        "Importing Modules",
        "import Statement",
        "from import",
        "as Keyword",
        "Built-in Modules",
        "math",
        "random",
        "statistics",
        "os",
        "sys",
        "Creating Packages",
        "Package Structure",
        "__init__.py",
        "Module Search Path",
      ],
    },

    {
      name: "Module 13 - Exception Handling",
      topics: [
        "Exception Introduction",
        "Syntax Errors",
        "Runtime Errors",
        "try",
        "except",
        "else",
        "finally",
        "Multiple Exceptions",
        "raise",
        "Custom Exceptions",
        "User-Defined Exceptions",
        "Exception Hierarchy",
        "Exception Handling Best Practices",
      ],
    },

    {
      name: "Module 14 - File Handling",
      topics: [
        "File Handling Introduction",
        "Opening Files",
        "Reading Files",
        "Writing Files",
        "Appending Files",
        "File Modes",
        "with Statement",
        "read()",
        "readline()",
        "readlines()",
        "write()",
        "writelines()",
        "Working with Directories",
        "os Module",
        "pathlib",
      ],
    },

    {
      name: "Module 15 - Object-Oriented Programming",
      topics: [
        "OOP Introduction",
        "Classes",
        "Objects",
        "Attributes",
        "Methods",
        "Constructors",
        "__init__()",
        "self",
        "Instance Variables",
        "Class Variables",
        "Instance Methods",
        "Class Methods",
        "Static Methods",
        "Encapsulation",
        "Properties",
      ],
    },

    {
      name: "Module 16 - OOPS,Inheritance & Polymorphism",
      topics: [
        "Inheritance",
        "Single Inheritance",
        "Multiple Inheritance",
        "Multilevel Inheritance",
        "Hierarchical Inheritance",
        "Hybrid Inheritance",
        "super()",
        "Method Overriding",
        "Polymorphism",
        "Duck Typing",
        "Method Resolution Order",
        "MRO",
        "Abstraction",
        "Abstract Classes",
        "ABC Module",
      ],
    },
    {
      name: "Module 17 - Projects & Interview Preparation",
      topics: [
        "Python Coding Practice",
        "Console Applications",
        "Calculator Project",
        "Python Interview Questions",
        "Python OOP Interview Questions",
        "Collections Interview Questions",
        "Exception Handling Questions",
        "File Handling Questions",
        "Advanced Python Questions",
        "Coding Interview Questions",
        "Output-Based Questions",
        "Mock Technical Interview",
        "Project Explanation",
        "HR Interview Preparation",
      ],
    },
  ],
},
  {
    title: "Java Full Stack Development",
    image: javaFullStack,
    category: "Full Stack",
    level: "Advanced",
    duration: "6 - 8 Months",
    mode: "Online Live",
    description:
      "Become a complete Java Full Stack Developer with frontend, backend and database skills.",
    topics: [
      "Core Java",
      "Advanced Java",
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Spring",
      "Spring Boot",
      "REST API",
      "MySQL",
      "JDBC",
      "Hibernate",
      "Git",
      "GitHub",
      "Authentication",
      "Deployment",
      "Real-Time Projects",
    ],
    modules: [
      {
        name: "HTML & CSS",
        topics: [
          "HTML5",
          "Semantic HTML",
          "Forms",
          "Tables",
          "CSS3",
          "Flexbox",
          "Grid",
          "Responsive Design",
        ],
      },
      {
        name: "JavaScript",
        topics: [
          "JavaScript Basics",
          "Variables",
          "Functions",
          "Arrays",
          "Objects",
          "DOM",
          "Events",
          "ES6",
          "Promises",
          "Async/Await",
        ],
      },
      {
        name: "React Development",
        topics: [
          "React Basics",
          "Components",
          "JSX",
          "Props",
          "State",
          "Hooks",
          "Forms",
          "Routing",
          "API Integration",
        ],
      },
      {
        name: "Java Backend",
        topics: [
          "Core Java",
          "OOP",
          "Collections",
          "Exception Handling",
          "Multithreading",
          "JDBC",
          "File Handling",
        ],
      },
      {
        name: "Spring Boot",
        topics: [
          "Spring Basics",
          "Dependency Injection",
          "Spring Boot",
          "REST APIs",
          "Spring Data JPA",
          "Hibernate",
          "Validation",
          "Security Basics",
        ],
      },
      {
        name: "Database & Projects",
        topics: [
          "MySQL",
          "SQL Queries",
          "Joins",
          "Subqueries",
          "Stored Procedures",
          "Database Design",
          "Git & GitHub",
          "Authentication",
          "Deployment",
          "Final Full Stack Project",
        ],
      },
    ],
  },
  {
    title: "Python Full Stack Development",
    image: pythonFullStack,
    category: "Full Stack",
    level: "Advanced",
    duration: "6 - 8 Months",
    mode: "Online Live",
    description:
      "Master full stack development using Python, Django, React and databases.",
    topics: [
      "Python",
      "Advanced Python",
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Django",
      "Flask",
      "REST API",
      "MySQL",
      "PostgreSQL",
      "Git",
      "Authentication",
      "Deployment",
      "Projects",
    ],
    modules: [
      {
        name: "Frontend Development",
        topics: [
          "HTML5",
          "CSS3",
          "Forms",
          "Flexbox",
          "Grid",
          "Responsive Design",
        ],
      },
      {
        name: "JavaScript",
        topics: [
          "JavaScript Basics",
          "Variables",
          "Functions",
          "Arrays",
          "Objects",
          "DOM",
          "ES6",
          "Promises",
          "Async/Await",
        ],
      },
      {
        name: "React Development",
        topics: [
          "React",
          "Components",
          "Props",
          "State",
          "Hooks",
          "Forms",
          "Routing",
          "API Integration",
        ],
      },
      {
        name: "Python Backend",
        topics: [
          "Python",
          "OOP",
          "Modules",
          "Packages",
          "Exception Handling",
          "File Handling",
          "Virtual Environment",
        ],
      },
      {
        name: "Django & Flask",
        topics: [
          "Django",
          "Models",
          "Views",
          "Templates",
          "URLs",
          "Forms",
          "Flask",
          "REST API",
        ],
      },
      {
        name: "Database & Projects",
        topics: [
          "MySQL",
          "PostgreSQL",
          "SQL",
          "Joins",
          "Database Design",
          "ORM",
          "Authentication",
          "Deployment",
          "Full Stack Project",
        ],
      },
    ],
  },
  {
    title: "MERN Stack Development",
    image: mernStack,
    category: "Full Stack",
    level: "Advanced",
    duration: "6 - 8 Months",
    mode: "Online Live",
    description:
      "Build modern web applications using MongoDB, Express, React and Node.js.",
    topics: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "REST API",
      "JWT",
      "Authentication",
      "Git",
      "GitHub",
      "Deployment",
      "Full Stack Projects",
    ],
    modules: [
      {
        name: "HTML & CSS",
        topics: [
          "HTML5",
          "Semantic HTML",
          "Forms",
          "CSS3",
          "Flexbox",
          "Grid",
          "Responsive Design",
        ],
      },
      {
        name: "JavaScript",
        topics: [
          "Variables",
          "Functions",
          "Arrays",
          "Objects",
          "ES6",
          "Promises",
          "Async/Await",
          "DOM",
        ],
      },
      {
        name: "React",
        topics: [
          "Components",
          "Props",
          "State",
          "Hooks",
          "Forms",
          "Routing",
          "API Integration",
          "React Project",
        ],
      },
      {
        name: "Node & Express",
        topics: [
          "Node.js",
          "NPM",
          "Express.js",
          "Middleware",
          "REST APIs",
          "Authentication",
          "JWT",
        ],
      },
      {
        name: "MongoDB",
        topics: [
          "MongoDB",
          "Collections",
          "Documents",
          "CRUD",
          "Queries",
          "Aggregation",
          "Mongoose",
        ],
      },
      {
        name: "MERN Projects",
        topics: [
          "Authentication",
          "Admin Panel",
          "REST API",
          "E-Commerce Project",
          "Dashboard",
          "Deployment",
          "Final MERN Project",
        ],
      },
    ],
  },
  {
    title: "Data Analyst with Generative AI",
    image: dataAnalytics,
    category: "Data & Analytics",
    level: "Beginner",
    duration: "4 - 5 Months",
    mode: "Online Live",
    badge: "Popular",
    description:
      "Become a job-ready Data Analyst with Advanced Excel, MySQL, Power BI, Python, Generative AI and GitHub skills.",
    topics: [
      "Advanced Excel",
      "MySQL",
      "Power BI",
      "Python",
      "Pandas",
      "NumPy",
      "Matplotlib",
      "Seaborn",
      "Data Cleaning",
      "Data Visualization",
      "Power Query",
      "Power Pivot",
      "DAX",
      "Dashboard Creation",
      "Generative AI",
      "Prompt Engineering",
      "ChatGPT",
      "Gemini",
      "Claude",
      "Perplexity",
      "Git",
      "GitHub",
      "Real-Time Projects",
      "Resume Preparation",
      "Mock Interviews",
    ],
    modules: [
      {
        name: "Excel - Introduction",
        topics: [
          "MS Office Versions",
          "Latest Excel Interface",
          "Rows and Columns",
          "Keyboard Shortcuts",
          "Data Entry",
          "Fill Series",
          "Find and Select",
          "Clear Options",
          "Ctrl + Enter",
          "Font Formatting",
          "Alignment",
          "Clipboard",
          "Copy and Paste Special",
        ],
      },
      {
        name: "Excel - Referencing & Arithmetic Functions",
        topics: [
          "Cell Referencing",
          "Absolute Referencing",
          "Relative Referencing",
          "Mixed Referencing",
          "Named Ranges",
          "Functions with Named Ranges",
          "SUM",
          "SUMIF",
          "SUMIFS",
          "COUNT",
          "COUNTA",
          "COUNTIFS",
          "AVERAGE",
          "AVERAGEIFS",
          "MAX",
          "MAXIFS",
          "MIN",
          "MINIFS",
        ],
      },
      {
        name: "Excel - Logical & Lookup Functions",
        topics: [
          "IF",
          "AND",
          "OR",
          "Nested IF",
          "IFS",
          "NOT",
          "IFERROR",
          "Nested Mathematical Functions",
          "Nested Logical Functions",
          "LOOKUP",
          "VLOOKUP",
          "Nested VLOOKUP",
          "HLOOKUP",
          "INDEX",
          "INDEX + MATCH",
          "INDIRECT",
          "OFFSET",
        ],
      },
      {
        name: "Excel - Advanced Functions",
        topics: [
          "Combining Arithmetic Functions",
          "Combining Logical Functions",
          "Combining Lookup Functions",
          "Nested Functions",
          "Data Validation",
          "Dependent Drop-down Lists",
        ],
      },
      {
        name: "Excel - Date & Text Functions",
        topics: [
          "DATE",
          "DAY",
          "MONTH",
          "YEAR",
          "YEARFRAC",
          "DATEDIF",
          "EOMONTH",
          "TEXT",
          "UPPER",
          "LOWER",
          "PROPER",
          "LEFT",
          "RIGHT",
          "SEARCH",
          "FIND",
          "MID",
          "TRIM",
          "Flash Fill",
        ],
      },
      {
        name: "Excel - Data Cleaning & Handling",
        topics: [
          "Data Cleaning",
          "Data Type Identification",
          "Number Formatting",
          "Formatting Shortcuts",
          "CTRL + T",
          "Excel Tables",
          "Table Formatting",
          "Remove Duplicates",
          "SORT",
          "Advanced Sort",
          "FILTER",
          "Advanced Filter",
        ],
      },
      {
        name: "Excel - Data Visualization",
        topics: [
          "Conditional Formatting",
          "Icon Sets",
          "Highlighted Colour Sets",
          "Data Bars",
          "Custom Formatting",
          "Bar Chart",
          "Column Chart",
          "Line Chart",
          "Scatter Chart",
          "Combo Chart",
          "Gantt Chart",
          "Waterfall Chart",
          "Pie Chart",
        ],
      },
      {
        name: "Excel - Pivot Tables & Dashboards",
        topics: [
          "Pivot Reports",
          "Pivot Table Interface",
          "Cross Table Reports",
          "Pivot Filters",
          "Pivot Charts",
          "Slicers",
          "Connecting Slicers",
          "Multiple Reports",
          "Calculated Fields",
          "Calculated Items",
          "Dashboard Types",
          "Dashboard Design",
          "Charts and Tables",
          "Colours and Shapes",
          "Dashboard Best Practices",
        ],
      },
      {
        name: "Excel - Power Query & Power Pivot",
        topics: [
          "Power Query Interface",
          "Power Query Tabs",
          "Import Excel Files",
          "Import Text Files",
          "Import External Sources",
          "Data Cleaning",
          "Data Transformation",
          "Load Queries",
          "Merge Queries",
          "Append Queries",
          "Power Pivot",
          "Pivot vs Power Pivot",
          "Database Connections",
          "Workbook Connections",
          "Web Data Connections",
        ],
      },
      {
        name: "MySQL - Database Fundamentals",
        topics: [
          "Introduction to Databases",
          "RDBMS",
          "Database Concepts",
          "Normalization",
          "Types of RDBMS",
          "MySQL Installation",
          "MySQL Workbench",
        ],
      },
      {
        name: "MySQL - SQL Commands & Data Types",
        topics: [
          "DDL",
          "DML",
          "DQL",
          "DCL",
          "TCL",
          "Numeric Data Types",
          "Character Data Types",
          "Date and Time Data Types",
        ],
      },
      {
        name: "MySQL - DQL & Operators",
        topics: [
          "SELECT",
          "LIMIT",
          "DISTINCT",
          "WHERE",
          "AND",
          "OR",
          "IN",
          "NOT IN",
          "BETWEEN",
          "EXISTS",
          "IS NULL",
          "IS NOT NULL",
          "Wildcards",
          "ORDER BY",
        ],
      },
      {
        name: "MySQL - CASE, NULL & Aggregations",
        topics: [
          "CASE WHEN THEN",
          "Logical SQL Problems",
          "NULL Handling",
          "IFNULL",
          "COALESCE",
          "GROUP BY",
          "HAVING",
          "COUNT",
          "SUM",
          "AVG",
          "MIN",
          "MAX",
          "String Functions",
          "Date & Time Functions",
        ],
      },
      {
        name: "MySQL - Constraints & Joins",
        topics: [
          "NOT NULL",
          "UNIQUE",
          "CHECK",
          "DEFAULT",
          "Primary Key",
          "Foreign Key",
          "Column Level Constraints",
          "Table Level Constraints",
          "INNER JOIN",
          "LEFT JOIN",
          "RIGHT JOIN",
          "CROSS JOIN",
          "SELF JOIN",
          "FULL OUTER JOIN Concepts",
        ],
      },
      {
        name: "MySQL - DDL, DML & TCL",
        topics: [
          "CREATE",
          "DROP",
          "ALTER",
          "RENAME",
          "TRUNCATE",
          "MODIFY",
          "COMMENT",
          "INSERT",
          "UPDATE",
          "DELETE",
          "COMMIT",
          "ROLLBACK",
          "SAVEPOINT",
          "Data Partitioning Concepts",
        ],
      },
      {
        name: "MySQL - Advanced SQL",
        topics: [
          "Indexes",
          "Types of Indexes",
          "Views",
          "Stored Procedures",
          "IN Parameters",
          "OUT Parameters",
          "INOUT Parameters",
          "User Defined Functions",
          "Window Functions",
          "RANK",
          "DENSE_RANK",
          "ROW_NUMBER",
          "LEAD",
          "LAG",
          "UNION",
          "UNION ALL",
          "INTERSECT",
          "Subqueries",
          "Multiple Queries",
          "Triggers",
        ],
      },
      {
        name: "Power BI - Fundamentals",
        topics: [
          "Power BI Introduction",
          "Power BI Installation",
          "Installation Checklist",
          "Power BI Desktop",
          "Power Query",
          "Desktop vs Power Query",
          "Power BI Interface",
          "Data Sources",
          "Visualization Types",
          "Loading Multiple Sources",
          "Data Types",
          "Default Visualizations",
          "Geo Location Maps",
        ],
      },
      {
        name: "Power BI - Dashboard & AI Visuals",
        topics: [
          "Financial Sample Data",
          "Sample Dashboard",
          "Map Visuals",
          "Map Variations",
          "Scatter Plot",
          "Play Axis",
          "AI Visuals",
          "AI Analysis",
          "Q&A Chatbot",
          "Hierarchy Tree",
        ],
      },
      {
        name: "Power BI - Visualization",
        topics: [
          "Column Chart",
          "Line Chart",
          "Conditional Formatting",
          "Visual Formatting",
          "Data Labels",
          "Axes Formatting",
          "Chart Customization",
        ],
      },
      {
        name: "Power Query Editor",
        topics: [
          "Power Query Editor",
          "Load Data from Folder",
          "Promote Headers",
          "Split Columns",
          "Delimiter",
          "Add Columns",
          "Append Queries",
          "Merge Queries",
          "Data Cleaning",
          "Data Transformation",
        ],
      },
      {
        name: "Power BI - Data Modelling",
        topics: [
          "Data Modelling",
          "Relationships",
          "Relationship Types",
          "Cardinality",
          "Filter Direction",
          "Multiple Data Sources",
          "Dashboard from Related Data",
          "Many-to-Many Relationships",
          "Active Relationships",
          "Inactive Relationships",
        ],
      },
      {
        name: "Power BI - Advanced Features",
        topics: [
          "Custom Column",
          "Conditional Column",
          "Manage Parameters",
          "Filters",
          "Filter Types",
          "Trend Analysis",
          "Future Forecast",
          "Tooltips",
          "Drill Down",
          "Drill Through",
          "Visual Interactions",
          "Buttons",
          "Bookmarks",
          "Navigation Buttons",
        ],
      },
      {
        name: "Power BI - DAX Fundamentals",
        topics: [
          "Introduction to DAX",
          "Calculated Columns",
          "DAX Measures",
          "Calculated Tables",
          "Calendar",
          "CALENDARAUTO",
          "SUMMARIZE",
          "GROUPBY",
          "RELATED",
          "LOOKUPVALUE",
          "SWITCH",
          "DATEDIFF",
          "RANKX",
          "Date Functions",
        ],
      },
      {
        name: "Power BI - DAX Aggregate Functions",
        topics: [
          "AVERAGE",
          "AVERAGEA",
          "AVERAGEX",
          "COUNT",
          "COUNTBLANK",
          "COUNTROWS",
          "COUNTX",
          "DISTINCTCOUNT",
          "DISTINCTCOUNTNOBLANK",
          "MAX",
          "MAXX",
          "SUM",
          "SUMX",
        ],
      },
      {
        name: "Power BI - DAX Date & Time",
        topics: [
          "CALENDAR",
          "HOUR",
          "MINUTE",
          "DATEDIFF",
          "NETWORKDAYS",
          "DAY",
          "QUARTER",
          "MONTH",
          "SECOND",
          "YEAR",
          "TIME",
          "NOW",
          "WEEKDAY",
          "TODAY",
          "WEEKNUM",
          "EOMONTH",
        ],
      },
      {
        name: "Power BI - DAX Text & Logical Functions",
        topics: [
          "COMBINEVALUES",
          "CONCATENATE",
          "CONCATENATEX",
          "EXACT",
          "SEARCH",
          "FIND",
          "FIXED",
          "LEFT",
          "RIGHT",
          "LEN",
          "UPPER",
          "MID",
          "REPLACE",
          "SUBSTITUTE",
          "REPT",
          "TRIM",
          "VALUE",
          "FORMAT",
          "IF",
          "AND",
          "OR",
          "NOT",
          "SWITCH",
          "COALESCE",
          "TRUE",
        ],
      },
      {
        name: "Power BI - DAX Filter & Information Functions",
        topics: [
          "CONTAINS",
          "CONTAINSROW",
          "HASONEFILTER",
          "HASONEVALUE",
          "ISFILTERED",
          "ISBLANK",
          "ISEMPTY",
          "ISEVEN",
          "USERNAME",
          "USERPRINCIPALNAME",
          "CALCULATE",
          "ALL",
          "ALLCROSSFILTERED",
          "ALLEXCEPT",
          "ALLSELECTED",
          "FILTER",
          "FIRST",
          "LAST",
          "LOOKUPVALUE",
          "SELECTEDVALUE",
        ],
      },
      {
        name: "Power BI - Time Intelligence",
        topics: [
          "OPENINGBALANCEMONTH",
          "OPENINGBALANCEQUARTER",
          "OPENINGBALANCEYEAR",
          "CLOSINGBALANCEMONTH",
          "CLOSINGBALANCEYEAR",
          "DATEADD",
          "DATESBETWEEN",
          "DATEINPERIOD",
          "DATESMTD",
          "DATESQTD",
          "DATESYTD",
          "ENDOFMONTH",
          "ENDOFYEAR",
          "FIRSTDATE",
          "FIRSTNONBLANK",
          "LASTDATE",
          "LASTNONBLANK",
          "NEXTDAY",
          "NEXTQUARTER",
          "NEXTYEAR",
          "YoY Analysis",
          "Running Total",
          "Rolling Average",
        ],
      },
      {
        name: "Power BI - Modelling & Service",
        topics: [
          "Model Relationships",
          "Edit Relationships",
          "Cardinality",
          "Cross Filter Direction",
          "Active Relationships",
          "Inactive Relationships",
          "USERELATIONSHIP",
          "Hiding Columns",
          "Refresh Data",
          "Remove Multiple Columns",
          "Avoiding Many-to-Many",
          "Home Tab Options",
          "New Visuals",
          "Text Box",
          "Linked Reports",
          "More Visuals",
          "Publish",
          "Power BI Service",
          "app.powerbi.com",
          "Schedule Refresh",
          "Dataflows",
          "PowerPoint Integration",
        ],
      },
      {
        name: "Power BI - Custom Visuals",
        topics: [
          "Custom Visuals",
          "Loading Custom Visuals",
          "Pinning Visuals",
          "Power BI Templates",
          "Publishing Reports",
        ],
      },
      {
        name: "Python for Data Analysis - Fundamentals",
        topics: [
          "Anaconda Installation",
          "Python Introduction",
          "Variables",
          "Integer",
          "Boolean",
          "Float",
          "List",
          "Tuple",
          "String",
          "Operators",
        ],
      },
      {
        name: "Python - Data Types & Collections",
        topics: [
          "Dictionaries",
          "Sequence Methods",
          "Concatenation",
          "Repetition",
          "len()",
          "min()",
          "max()",
          "Indexing",
          "Position",
          "Adding Elements",
          "Deleting Elements",
          "Reverse",
          "Sorting",
        ],
      },
      {
        name: "Python - Sets, Regex & Decisions",
        topics: [
          "Sets",
          "Set Theory",
          "Regular Expressions",
          "re Module",
          "findall",
          "search",
          "split",
          "match",
          "if",
          "elif",
          "User Input",
          "Identity Operators",
        ],
      },
      {
        name: "Python - Loops & Functions",
        topics: [
          "for Loop",
          "while Loop",
          "Functions",
          "Function Arguments",
          "Return Values",
          "Lambda Functions",
          "Modules",
          "Math Module",
          "Calendar Module",
          "Date & Time Module",
        ],
      },
      {
        name: "Python - Pandas, NumPy & Visualization",
        topics: [
          "NumPy Introduction",
          "Pandas Introduction",
          "DataFrame Creation",
          "Reading Data",
          "Data Cleaning",
          "Data Transformation",
          "Pandas Analysis",
          "University Dataset Analysis",
          "Salary Dataset Analysis",
          "Matplotlib",
          "Seaborn",
          "Data Visualization",
        ],
      },
      {
        name: "Generative AI - Fundamentals",
        topics: [
          "Introduction to AI",
          "AI Revolution",
          "Artificial Intelligence Fundamentals",
          "Machine Learning",
          "Deep Learning",
          "Generative AI",
          "ML vs DL vs GenAI",
          "History of AI",
          "AI Applications",
          "AI Career Opportunities",
          "What is Generative AI?",
          "How Generative AI Works",
          "Tokens",
          "Context Window",
          "Temperature",
          "Hallucinations",
          "AI Ethics",
          "Responsible AI",
          "AI Limitations",
        ],
      },
      {
        name: "Generative AI - LLMs",
        topics: [
          "Large Language Models",
          "What are LLMs?",
          "How LLMs are Trained",
          "Transformer Architecture",
          "High-Level Transformer Concepts",
          "Choosing the Right Model",
        ],
      },
      {
        name: "AI Tools for Data Analysts",
        topics: [
          "ChatGPT",
          "Google Gemini",
          "Claude",
          "Perplexity",
          "AI Tools Ecosystem",
          "AI Coding Assistants",
          "Cursor AI",
        ],
      },
      {
        name: "Prompt Engineering",
        topics: [
          "Introduction to Prompt Engineering",
          "Anatomy of an Effective Prompt",
          "Prompt Best Practices",
          "Structured Output Prompting",
          "Prompt Optimization",
          "Prompt Debugging",
          "Prompt Libraries",
          "Business Prompt Engineering",
        ],
      },
      {
        name: "Practical AI for Data Analysts",
        topics: [
          "AI for Excel Automation",
          "AI for SQL Query Writing",
          "AI for Python Coding",
          "AI for Power BI",
          "AI for DAX",
          "AI Dashboard Design",
          "AI Report Generation",
          "AI Resume Builder",
          "AI Mock Interviews",
          "AI Productivity Techniques",
        ],
      },
      {
        name: "Git & GitHub for Data Analysts",
        topics: [
          "Introduction to Git",
          "Version Control",
          "Installing Git",
          "GitHub Setup",
          "Git Commands",
          "Repository Management",
          "Creating Repositories",
          "Cloning Repositories",
          "GitHub Interface",
          "Branching",
          "Merging",
          "Commit",
          "Push",
          "Pull",
          "Uploading Excel Projects",
          "Uploading SQL Projects",
          "Uploading Python Projects",
          "GitHub Collaboration",
          "README Creation",
          "Portfolio Building",
          "Version Tracking",
        ],
      },
      {
        name: "Real-Time Data Analytics Projects",
        topics: [
          "Sales Data Analysis",
          "Customer Analysis",
          "Financial Analysis",
          "Excel Dashboard Project",
          "MySQL Analytics Project",
          "Power BI Business Dashboard",
          "Python Data Analysis Project",
          "Generative AI Data Analysis",
          "End-to-End Data Analytics Project",
          "GitHub Portfolio Project",
        ],
      },
      {
        name: "Interview & Career Preparation",
        topics: [
          "Data Analyst Interview Questions",
          "Excel Interview Questions",
          "SQL Interview Questions",
          "Power BI Interview Questions",
          "Python Interview Questions",
          "DAX Interview Questions",
          "Generative AI Interview Questions",
          "Resume Preparation",
          "Resume Optimization",
          "Mock Interviews",
          "Technical Interviews",
          "HR Interviews",
          "Aptitude",
          "Communication Skills",
          "Placement Preparation",
        ],
      },
    ],
  },
  {
    title: "Generative AI",
    image: genaiLogo,
    category: "AI & Emerging Tech",
    level: "Advanced",
    duration: "3 - 5 Months",
    mode: "Online Live",
    badge: "New",
    description:
      "Explore Generative AI, LLMs, prompt engineering, RAG and AI agents.",
    topics: [
      "AI Fundamentals",
      "Machine Learning Basics",
      "Generative AI",
      "Prompt Engineering",
      "LLMs",
      "ChatGPT",
      "GPT Models",
      "Embeddings",
      "Vector Databases",
      "LangChain",
      "RAG",
      "AI Agents",
      "API Integration",
      "AI Projects",
    ],
    modules: [
      {
        name: "AI Fundamentals",
        topics: [
          "Artificial Intelligence",
          "Machine Learning",
          "Deep Learning",
          "Neural Networks",
          "AI Applications",
        ],
      },
      {
        name: "Generative AI",
        topics: [
          "Generative Models",
          "LLMs",
          "Transformers",
          "GPT Models",
          "Text Generation",
          "AI Applications",
        ],
      },
      {
        name: "Prompt Engineering",
        topics: [
          "Prompt Basics",
          "Zero-Shot Prompting",
          "Few-Shot Prompting",
          "Role Prompting",
          "Structured Prompts",
          "Prompt Optimization",
        ],
      },
      {
        name: "LangChain & RAG",
        topics: [
          "LangChain",
          "Embeddings",
          "Vector Database",
          "Document Loading",
          "Retrieval",
          "RAG Applications",
        ],
      },
      {
        name: "AI Agents",
        topics: [
          "AI Agents",
          "Tools",
          "Memory",
          "Agent Workflows",
          "Automation",
          "Agent Applications",
        ],
      },
      {
        name: "AI Projects",
        topics: [
          "AI Chatbot",
          "Document Assistant",
          "RAG Application",
          "AI Agent",
          "API Integration",
          "Final AI Project",
        ],
      },
    ],
  },
  {
    title: "DevOps with AWS",
    image: devopsLogo,
    category: "Cloud & DevOps",
    level: "Advanced",
    duration: "3 - 4 Months",
    mode: "Online Live",
    badge: "Popular",
    description:
      "Master Linux, AWS Cloud, Docker, Kubernetes, Terraform, Ansible, CI/CD, GitOps, DevSecOps, monitoring and real-world cloud deployment.",
    topics: [
      "DevOps",
      "SDLC",
      "Agile & Scrum",
      "SRE",
      "Linux",
      "Shell Scripting",
      "Networking",
      "AWS",
      "EC2",
      "S3",
      "IAM",
      "VPC",
      "RDS",
      "ECR",
      "ECS",
      "Lambda",
      "CloudWatch",
      "Git",
      "GitHub",
      "Jenkins",
      "GitHub Actions",
      "Maven",
      "SonarQube",
      "JFrog",
      "Terraform",
      "Ansible",
      "Docker",
      "Kubernetes",
      "EKS",
      "Helm",
      "ArgoCD",
      "Prometheus",
      "Grafana",
      "ELK",
      "DevSecOps",
      "AI for DevOps",
      "Real-Time Projects",
    ],
    modules: [
      {
        name: "Module 1 - DevOps Fundamentals & SDLC",
        topics: [
          "What is DevOps",
          "DevOps Culture",
          "DevOps Lifecycle",
          "DevOps Benefits",
          "DevOps vs Traditional IT",
          "Plan",
          "Code",
          "Build",
          "Test",
          "Release",
          "Deploy",
          "Monitor",
          "Software Development Life Cycle",
          "Agile Methodology",
          "Scrum Framework",
          "Sprint Planning",
          "Product Backlog",
          "Daily Stand-ups",
          "Jira Issue Tracking",
          "Continuous Integration",
          "Continuous Delivery",
          "Continuous Deployment",
          "Infrastructure as Code",
          "Monitoring & Feedback Loops",
        ],
      },
      {
        name: "Module 2 - SRE Foundations",
        topics: [
          "Site Reliability Engineering",
          "DevOps and SRE",
          "Reliability Engineering",
          "Service Level Indicators",
          "SLI",
          "SLO",
          "SLA",
          "Error Budgets",
          "Reliability vs Velocity",
          "Toil Reduction",
          "Automation",
          "Reliability Best Practices",
        ],
      },
      {
        name: "Module 3 - Linux & Shell Scripting",
        topics: [
          "Linux Fundamentals",
          "Linux Architecture",
          "Linux File System",
          "File Permissions",
          "Users & Groups",
          "Package Management",
          "yum",
          "apt",
          "Process Management",
          "top",
          "ps",
          "kill",
          "Disk Management",
          "Memory Management",
          "Networking Commands",
          "netstat",
          "curl",
          "wget",
          "SSH",
          "Server Access",
          "Shell Scripting",
          "Variables",
          "Loops",
          "Conditions",
          "Functions",
          "Arguments",
          "File Handling",
          "Logging",
          "Cron Jobs",
          "Crontab",
          "Systemd",
          "systemctl",
          "Service Management",
        ],
      },
      {
        name: "Module 4 - Networking Fundamentals",
        topics: [
          "OSI Model",
          "TCP/IP Model",
          "IP Addressing",
          "CIDR",
          "Subnetting",
          "Public IP",
          "Private IP",
          "DNS",
          "HTTP",
          "HTTPS",
          "SSL/TLS",
          "Load Balancing",
          "Reverse Proxy",
          "Nginx",
        ],
      },
      {
        name: "Module 5 - Cloud Computing & AWS",
        topics: [
          "Cloud Computing",
          "IaaS",
          "PaaS",
          "SaaS",
          "Public Cloud",
          "Private Cloud",
          "AWS Global Infrastructure",
          "AWS Regions",
          "Availability Zones",
          "EC2",
          "EC2 Instances",
          "AMI",
          "Key Pairs",
          "S3",
          "S3 Storage",
          "S3 Lifecycle",
          "IAM",
          "IAM Users",
          "IAM Roles",
          "IAM Policies",
          "VPC",
          "Subnets",
          "Route Tables",
          "NAT Gateway",
          "Internet Gateway",
          "EBS",
          "EFS",
          "Security Groups",
          "NACLs",
          "ECR",
          "ECS",
        ],
      },
      {
        name: "Module 6 - Advanced AWS Services",
        topics: [
          "Application Load Balancer",
          "Network Load Balancer",
          "Auto Scaling Groups",
          "Route 53",
          "CloudFront",
          "RDS",
          "DynamoDB",
          "CloudTrail",
          "Systems Manager",
          "Parameter Store",
          "Patch Manager",
          "Session Manager",
          "SQS",
          "SNS",
          "AWS CLI",
          "CloudWatch",
          "CloudWatch Logs",
          "CloudWatch Metrics",
          "CloudWatch Alerts",
          "AWS Lambda",
          "API Gateway",
        ],
      },
      {
        name: "Module 7 - AWS Cost Optimization",
        topics: [
          "AWS Pricing Basics",
          "EC2 Pricing",
          "Spot Instances",
          "Reserved Instances",
          "On-Demand Instances",
          "AWS Budgets",
          "Billing Alerts",
          "Savings Plans",
          "Cost Optimization Best Practices",
        ],
      },
      {
        name: "Module 8 - AWS CLI & Terraform Preview",
        topics: [
          "AWS CLI Installation",
          "AWS CLI Configuration",
          "aws ec2 run-instances",
          "aws ec2 create-vpc",
          "aws ec2 create-subnet",
          "aws ec2 create-security-group",
          "aws rds create-db-instance",
          "Infrastructure as Code",
          "Terraform Introduction",
          "AWS Provider",
          "main.tf",
          "VPC with Terraform",
          "EC2 with Terraform",
          "Security Group with Terraform",
          "RDS with Terraform",
          "terraform init",
          "terraform plan",
          "terraform apply",
          "terraform destroy",
        ],
      },
      {
        name: "Module 9 - Git & GitHub",
        topics: [
          "Version Control",
          "Git Installation",
          "Git Configuration",
          "Git Workflow",
          "git clone",
          "git add",
          "git commit",
          "git push",
          "git pull",
          "Branching",
          "Merging",
          "GitFlow",
          "Trunk-Based Development",
          "Rebase",
          "Merge",
          "Cherry-Pick",
          "Stash",
          "GitHub Repositories",
          "Pull Requests",
          "Code Reviews",
          "Repository Management",
          "GitHub Actions",
        ],
      },
      {
        name: "Module 10 - CI/CD Pipelines",
        topics: [
          "CI/CD Concepts",
          "Pipeline Stages",
          "Build",
          "Test",
          "Deploy",
          "Pipeline as Code",
          "Jenkins",
          "Jenkins Installation",
          "Freestyle Jobs",
          "Pipeline Jobs",
          "Jenkins Master-Agent Architecture",
          "GitHub Actions",
          "YAML Pipelines",
          "Secrets",
          "Environment Variables",
          "Self-Hosted Runners",
          "Maven",
          "SonarQube",
          "Nexus",
          "JFrog",
        ],
      },
      {
        name: "Module 11 - End-to-End CI/CD",
        topics: [
          "Java Spring Boot CI/CD",
          "Git Push",
          "Security Check",
          "Unit Testing",
          "Maven Package",
          "SonarQube Scan",
          "Docker Build",
          "Push Image to ECR",
          "Deploy to EC2",
          "Deploy to ECS",
          "JFrog Integration",
          "Ansible Integration",
          "Jenkins Pipeline",
          "GitHub Actions Pipeline",
        ],
      },
      {
        name: "Module 12 - Terraform Infrastructure as Code",
        topics: [
          "Terraform Architecture",
          "Providers",
          "Resources",
          "Variables",
          "Outputs",
          "State Management",
          "Remote Backend",
          "Terraform Modules",
          "Data Sources",
          "locals",
          "terraform.tfvars",
          "Workspaces",
          "Development Environment",
          "Staging Environment",
          "Production Environment",
          "terraform fmt",
          "terraform validate",
          "terraform import",
          "terraform taint Concepts",
          "Infrastructure Drift",
          "terraform plan",
          "S3 Remote Backend",
          "State Locking Concepts",
        ],
      },
      {
        name: "Module 13 - Terraform Hands-On Projects",
        topics: [
          "3-Tier AWS Architecture",
          "VPC using Terraform",
          "EC2 using Terraform",
          "RDS using Terraform",
          "Terraform Modules",
          "S3 Remote Backend",
          "State Management",
          "State Conflict Simulation",
          "Infrastructure Drift Detection",
          "Terraform in GitHub Actions",
        ],
      },
      {
        name: "Module 14 - Ansible Configuration Management",
        topics: [
          "Ansible Introduction",
          "Ansible Architecture",
          "Installation",
          "Inventory",
          "Playbooks",
          "Modules",
          "Roles",
          "Templates",
          "Web Server Setup",
          "Application Deployment",
          "Multi-Node Automation",
          "Ansible Vault",
          "Secrets Management",
          "Dynamic AWS Inventory",
          "Ansible Galaxy",
          "Community Roles",
          "Java Deployment",
          "Multi-Server Deployment",
        ],
      },
      {
        name: "Module 15 - Docker Containerization",
        topics: [
          "Docker Introduction",
          "Containers",
          "Images",
          "Dockerfile",
          "Docker Commands",
          "Container Lifecycle",
          "Docker Networking",
          "Volumes",
          "Docker Compose",
          "Multi-Stage Builds",
          "Docker Security",
          "Docker Hub",
          "AWS ECR",
          "Image Management",
        ],
      },
      {
        name: "Module 16 - Kubernetes",
        topics: [
          "Kubernetes Introduction",
          "Cluster Architecture",
          "Control Plane",
          "Worker Nodes",
          "Pods",
          "ReplicaSets",
          "Deployments",
          "Services",
          "ConfigMaps",
          "Secrets",
          "Ingress",
          "Persistent Volumes",
          "RBAC",
          "Network Policies",
          "Helm Charts",
          "Horizontal Pod Autoscaling",
          "Rolling Updates",
          "Rollback",
          "Blue-Green Deployment",
          "Canary Deployment",
          "Deployment Strategies",
        ],
      },
      {
        name: "Module 17 - Kubernetes Production & EKS",
        topics: [
          "Production Kubernetes",
          "EKS",
          "Amazon EKS",
          "EKS Architecture",
          "EKS Networking",
          "Terraform EKS",
          "Cluster Management",
          "Pod Troubleshooting",
          "CrashLoopBackOff",
          "Deployment Debugging",
          "Logs",
          "Resource Management",
          "Auto Scaling",
        ],
      },
      {
        name: "Module 18 - GitOps & ArgoCD",
        topics: [
          "GitOps Principles",
          "ArgoCD",
          "Flux",
          "Continuous Deployment",
          "Git-Based Deployment",
          "Pull Deployment Model",
          "Push Deployment Model",
          "ArgoCD Installation",
          "ArgoCD on EKS",
          "Application CRDs",
          "Sync Policies",
          "Health Checks",
          "App-of-Apps Pattern",
          "Automated Drift Detection",
          "Auto-Sync",
          "Self-Healing",
          "RBAC",
          "SSO Integration",
        ],
      },
      {
        name: "Module 19 - Cloud Native Projects",
        topics: [
          "Java Spring Boot on Kubernetes",
          "GitHub Actions",
          "Docker",
          "Helm",
          "ArgoCD",
          "EKS",
          "GitOps",
          "Auto Scaling",
          "Rolling Deployment",
          "Rollback",
          "Python Agentic AI Application",
          "Dockerized AI Agents",
          "AWS ECR",
          "Kubernetes Deployment",
        ],
      },
      {
        name: "Module 20 - Monitoring & Observability",
        topics: [
          "Monitoring Fundamentals",
          "Observability",
          "Prometheus",
          "Prometheus Metrics",
          "Grafana",
          "Grafana Dashboards",
          "ELK Stack",
          "Elasticsearch",
          "Logstash",
          "Kibana",
          "Jaeger",
          "Distributed Tracing",
          "Alertmanager",
          "Prometheus Alerts",
          "Slack Alerts",
          "PagerDuty",
          "OpsGenie",
          "AWS CloudWatch",
          "CloudWatch Logs",
          "CloudWatch Metrics",
          "SLIs",
          "SLOs",
          "Error Budgets",
        ],
      },
      {
        name: "Module 21 - DevSecOps",
        topics: [
          "DevSecOps Fundamentals",
          "Secure CI/CD",
          "IAM Best Practices",
          "Secrets Management",
          "Trivy",
          "Container Scanning",
          "Snyk",
          "Dependency Scanning",
          "SAST",
          "SonarQube",
          "Semgrep",
          "DAST",
          "OWASP ZAP",
          "OWASP Top 10",
          "Injection",
          "Broken Authentication",
          "SSRF",
          "Container Hardening",
          "Non-Root Containers",
          "Minimal Base Images",
          "Distroless Images",
          "Read-Only Filesystems",
          "SBOM",
          "Syft",
          "Grype",
          "OPA",
          "Gatekeeper",
          "Policy as Code",
          "AWS GuardDuty",
          "AWS Security Hub",
        ],
      },
      {
        name: "Module 22 - AI Tools for DevOps",
        topics: [
          "ChatGPT",
          "GitHub Copilot",
          "Claude Code",
          "Cursor",
          "AI for CI/CD",
          "AI-Based Debugging",
          "AI Log Analysis",
          "AI Automation",
          "Prompt Engineering",
          "DevOps Prompt Design",
          "Automating DevOps Tasks",
        ],
      },
      {
        name: "Module 23 - Real-Time DevOps Projects",
        topics: [
          "Project 1 - AWS Auto Scaling & VPC Architecture",
          "VPC",
          "Subnets",
          "ALB",
          "Auto Scaling",
          "CloudWatch",
          "Project 2 - AWS Infrastructure with Terraform",
          "Terraform",
          "VPC",
          "EC2",
          "Load Balancer",
          "S3 Remote Backend",
          "Project 3 - End-to-End CI/CD Pipeline",
          "Maven",
          "SonarQube",
          "Docker",
          "Jenkins",
          "GitHub Actions",
          "Project 4 - Ansible Configuration Management",
          "Java",
          "Tomcat",
          "Multi-Node Deployment",
        ],
      },
      {
        name: "Module 24 - Advanced Cloud Native Projects",
        topics: [
          "Project 5 - Kubernetes + EKS + GitOps",
          "Kubernetes",
          "Helm",
          "ArgoCD",
          "EKS",
          "Auto Scaling",
          "Project 6 - Monitoring & Observability",
          "Prometheus",
          "Grafana",
          "ELK Stack",
          "Project 7 - CI/CD for Agentic AI App",
          "Python Agentic AI",
          "GitHub Actions",
          "Jenkins",
          "Docker",
          "SonarQube",
          "AWS ECR",
          "EC2",
          "ECS",
          "Project 8 - Agentic AI on Kubernetes",
          "AI Agent Containers",
          "AWS ECR",
          "Kubernetes",
          "EKS",
          "ArgoCD",
          "GitOps",
          "Automated Rollback",
        ],
      },
      {
        name: "Module 25 - DevOps Interview & Career Preparation",
        topics: [
          "DevOps Interview Questions",
          "Linux Interview Questions",
          "AWS Interview Questions",
          "Docker Interview Questions",
          "Kubernetes Interview Questions",
          "Terraform Interview Questions",
          "Ansible Interview Questions",
          "Jenkins Interview Questions",
          "GitHub Actions Interview Questions",
          "CI/CD Scenario Questions",
          "Cloud Architecture Questions",
          "Troubleshooting Scenarios",
          "Production Incident Scenarios",
          "Resume Preparation",
          "Resume Optimization",
          "GitHub Portfolio",
          "Mock Technical Interviews",
          "HR Interview Preparation",
        ],
      },
    ],
  },
  {
    title: "Java + SQL + Interview Preparation",
    image: javaSqlLogo,
    category: "Career Preparation",
    level: "Beginner",
    duration: "4 - 5 Months",
    mode: "Online Live",
    badge: "Career",
    description:
      "Complete Java, SQL and interview preparation program with mock interviews.",
    topics: [
      "Core Java",
      "OOP",
      "Collections",
      "Exception Handling",
      "Multithreading",
      "JDBC",
      "SQL",
      "Joins",
      "Subqueries",
      "Database Concepts",
      "Java Coding Questions",
      "SQL Interview Questions",
      "Resume Preparation",
      "HR Interview",
      "Technical Interview",
      "Mock Interviews",
      "Aptitude",
      "Communication",
      "Problem Solving",
      "Placement Preparation",
    ],
    modules: [
      {
        name: "Core Java",
        topics: [
          "Java Fundamentals",
          "Variables",
          "Data Types",
          "Operators",
          "Control Statements",
          "Arrays",
          "Strings",
          "Methods",
        ],
      },
      {
        name: "Java OOP",
        topics: [
          "Classes & Objects",
          "Constructors",
          "Inheritance",
          "Polymorphism",
          "Abstraction",
          "Encapsulation",
          "Interfaces",
        ],
      },
      {
        name: "Java Advanced Concepts",
        topics: [
          "Collections",
          "Generics",
          "Exception Handling",
          "Multithreading",
          "File Handling",
          "JDBC",
          "Database Connectivity",
        ],
      },
      {
        name: "SQL & Database",
        topics: [
          "SQL Basics",
          "SELECT",
          "WHERE",
          "ORDER BY",
          "GROUP BY",
          "HAVING",
          "Joins",
          "Subqueries",
          "Aggregate Functions",
          "Constraints",
          "Normalization",
          "Database Design",
        ],
      },
      {
        name: "Technical Interview Preparation",
        topics: [
          "Java Interview Questions",
          "SQL Interview Questions",
          "Coding Questions",
          "Problem Solving",
          "Data Structures Basics",
          "Technical Discussion",
          "Programming Practice",
        ],
      },
      {
        name: "HR & Mock Interviews",
        topics: [
          "Resume Preparation",
          "Self Introduction",
          "HR Questions",
          "Communication Skills",
          "Mock Technical Interview",
          "Mock HR Interview",
          "Interview Feedback",
          "Aptitude",
          "Placement Preparation",
        ],
      },
    ],
  },
  {
    title: "Python + SQL + Interview Preparation",
    image: pythonLogo,
    category: "Career Preparation",
    level: "Beginner",
    duration: "4 - 5 Months",
    mode: "Online Live",
    badge: "Career",
    description:
      "Complete Python, SQL and interview preparation course with coding practice and mock interviews.",
    topics: [
      "Python Fundamentals",
      "Advanced Python",
      "OOP in Python",
      "Collections",
      "Exception Handling",
      "File Handling",
      "Python Libraries",
      "SQL",
      "Joins",
      "Subqueries",
      "Aggregate Functions",
      "Database Concepts",
      "Python Coding Questions",
      "SQL Interview Questions",
      "Resume Preparation",
      "HR Interview",
      "Technical Interview",
      "Mock Interviews",
      "Aptitude",
      "Communication Skills",
      "Problem Solving",
      "Placement Preparation",
    ],
    modules: [
      {
        name: "Python Fundamentals",
        topics: [
          "Python Introduction",
          "Installation",
          "Variables",
          "Data Types",
          "Operators",
          "Input & Output",
          "Type Casting",
          "Control Statements",
        ],
      },
      {
        name: "Python OOP & Advanced",
        topics: [
          "Classes & Objects",
          "Constructors",
          "Inheritance",
          "Polymorphism",
          "Encapsulation",
          "Abstraction",
          "Exception Handling",
          "File Handling",
          "Modules & Packages",
        ],
      },
      {
        name: "Python Libraries",
        topics: [
          "NumPy",
          "Pandas",
          "Matplotlib",
          "Requests",
          "JSON",
          "Regular Expressions",
          "Data Processing",
          "API Integration",
        ],
      },
      {
        name: "SQL & Database",
        topics: [
          "SQL Basics",
          "SELECT",
          "WHERE",
          "ORDER BY",
          "GROUP BY",
          "HAVING",
          "Joins",
          "Subqueries",
          "Aggregate Functions",
          "Constraints",
          "Normalization",
          "Database Design",
        ],
      },
      {
        name: "Technical Interview Preparation",
        topics: [
          "Python Interview Questions",
          "SQL Interview Questions",
          "Python Coding Questions",
          "Problem Solving",
          "Data Structures Basics",
          "Logical Questions",
          "Technical Discussion",
          "Coding Practice",
        ],
      },
      {
        name: "HR & Mock Interviews",
        topics: [
          "Resume Preparation",
          "Self Introduction",
          "HR Questions",
          "Communication Skills",
          "Mock Technical Interview",
          "Mock HR Interview",
          "Interview Feedback",
          "Aptitude",
          "Placement Preparation",
        ],
      },
    ],
  },
];
const s = {
  page: { fontFamily: "Inter, Arial, sans-serif", color: "#153c43", background: "#fff", minHeight: "100vh" },
  hero: { minHeight: 420, padding: "70px 6%", display: "flex", alignItems: "center", background: "linear-gradient(90deg, rgba(1,58,59,.97), rgba(1,58,59,.82), rgba(1,58,59,.25)), url('https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=90') center/cover" },
  container: { width: "min(1200px, calc(100% - 30px))", margin: "auto" },
  title: { fontFamily: "Georgia, serif", color: "#fff", fontSize: "clamp(40px, 5vw, 62px)", lineHeight: 1, margin: 0 },
  gold: { color: "#efbe4b" },
  search: { marginTop: -28, position: "relative", zIndex: 3, background: "#fff", padding: 16, borderRadius: 16, boxShadow: "0 12px 35px rgba(0,60,60,.15)", display: "flex", gap: 9, flexWrap: "wrap" },
  input: { height: 45, border: "1px solid #d7e6e4", borderRadius: 9, padding: "0 13px", fontSize: 13, outline: "none" },
  select: { height: 45, border: "1px solid #d7e6e4", borderRadius: 9, padding: "0 12px", fontSize: 13, background: "#fff", color: "#264b50", cursor: "pointer", position: "relative", zIndex: 10 },
  filters: { marginTop: 20, padding: 15, border: "1px solid #dce9e7", borderRadius: 12, background: "#f7fbfa", display: "flex", gap: 18, flexWrap: "wrap", alignItems: "center" },
  check: { display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "#38585d" },
  section: { padding: "38px 0" },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))", gap: 17 },
  card: { position: "relative", background: "linear-gradient(145deg,#f7fcfb,#edf7f5)", border: "1px solid #dcebe9", borderRadius: 14, padding: 15, display: "flex", flexDirection: "column", minHeight: 520, boxShadow: "0 5px 15px rgba(0,70,70,.05)" },
  image: { width: "100%", height: 135, objectFit: "contain", background: "#fff", borderRadius: 10, padding: 12 },
  badge: { position: "absolute", top: 12, right: 12, background: "#08706d", color: "#fff", borderRadius: 15, padding: "5px 10px", fontSize: 10, fontWeight: 800, zIndex: 2 },
  cardTitle: { fontFamily: "Georgia, serif", color: "#113c43", fontSize: 19, lineHeight: 1.15, margin: "14px 0 7px" },
  description: { color: "#596b70", fontSize: 12, lineHeight: 1.45, minHeight: 50, margin: 0 },
  topicWrap: { display: "flex", flexWrap: "wrap", gap: 6, margin: "10px 0", maxHeight: 118, overflow: "hidden" },
  topic: { background: "#fff", border: "1px solid #d7e7e4", borderRadius: 20, padding: "5px 8px", color: "#456267", fontSize: 10.5, whiteSpace: "nowrap" },
  btn: { border: 0, borderRadius: 23, background: "#075d5d", color: "#fff", height: 40, fontSize: 12, fontWeight: 800, cursor: "pointer", width: "100%" },
  modalBack: { position: "fixed", inset: 0, zIndex: 9999, background: "rgba(4,31,34,.78)", display: "flex", justifyContent: "center", alignItems: "center", padding: 15 },
  modal: { width: "min(1000px,100%)", height: "92vh", maxHeight: "92vh", overflow: "hidden", background: "#fff", borderRadius: 18, boxShadow: "0 25px 70px rgba(0,0,0,.35)", display: "flex", flexDirection: "column" },
  modalHead: { padding: "20px 23px", background: "linear-gradient(135deg,#075d5d,#0b7370)", color: "#fff", display: "flex", justifyContent: "space-between", gap: 15, flexShrink: 0 },
  close: { border: 0, background: "rgba(255,255,255,.15)", color: "#fff", borderRadius: "50%", width: 35, height: 35, fontSize: 22, cursor: "pointer", flexShrink: 0, display: "flex", alignItems: "center", justifyContent: "center", lineHeight: 1 },
  content: { display: "grid", gridTemplateColumns: "280px minmax(0,1fr)", flex: 1, minHeight: 0, overflow: "hidden" },
  modules: { background: "#f3f9f7", borderRight: "1px solid #dce9e7", padding: 15, overflowY: "auto", minHeight: 0 },
  module: { width: "100%", border: "1px solid #dce9e7", background: "#fff", borderRadius: 9, padding: "13px 12px", marginBottom: 8, color: "#28555a", fontWeight: 700, cursor: "pointer", textAlign: "left", fontSize: 12, display: "block" },
  activeModule: { background: "#075d5d", color: "#fff", borderColor: "#075d5d", boxShadow: "0 5px 12px rgba(0,80,80,.15)" },
  topicContent: { padding: 23, overflowY: "auto", minWidth: 0, minHeight: 0 },
  topicCards: { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(190px,1fr))", gap: 11, marginTop: 17 },
  topicCard: { padding: "14px 13px", borderRadius: 11, background: "linear-gradient(135deg,#f4faf8,#fff)", border: "1px solid #dce9e7", boxShadow: "0 4px 12px rgba(0,70,70,.05)", color: "#34575c", fontSize: 12, fontWeight: 700 },
  footer: { padding: "15px 22px", borderTop: "1px solid #e0e9e7", display: "flex", gap: 10, flexWrap: "wrap", flexShrink: 0, background: "#fff", position: "relative", zIndex: 2 },

};

function CourseCard({ course, onModules, onEnquire }) {
  return (
    <article style={s.card}>
      {course.badge && <span style={s.badge}>{course.badge}</span>}
      <img src={course.image} alt={course.title} style={s.image} />
      <h3 style={s.cardTitle}>{course.title}</h3>
      <p style={s.description}>{course.description}</p>
      <div style={s.topicWrap}>
        {course.topics.map((topic, i) => (
          <span key={i} style={s.topic}>{topic}</span>
        ))}
      </div>
      <div style={{ display: "flex", justifyContent: "space-between", gap: 8, margin: "auto 0 10px", fontSize: 11, fontWeight: 800, color: "#31565b" }}>
        <span>◷ {course.duration}</span>
        <span>{course.level}</span>
      </div>
      <button style={s.btn} onClick={() => onModules(course)}>View Modules →</button>
      <button style={{ ...s.btn, marginTop: 8, background: "#efbe4b", color: "#173d42" }} onClick={onEnquire}>Enquire Now →</button>
    </article>
  );
}

function CourseModal({ course, onClose, navigate }) {
  const [activeModule, setActiveModule] = useState(course.modules[0]);

  React.useEffect(() => {
    const key = (e) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", key);
    document.body.style.overflow = "hidden";
    return () => {
      document.removeEventListener("keydown", key);
      document.body.style.overflow = "";
    };
  }, [onClose]);

  return (
    <div
      style={s.modalBack}
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div style={s.modal}>
        <div style={s.modalHead}>
          <div>
            <div style={{ fontSize: 10, letterSpacing: 2, fontWeight: 800, marginBottom: 5 }}>COURSE CURRICULUM</div>
            <h2 style={{ fontFamily: "Georgia,serif", fontSize: "clamp(22px,3vw,30px)", margin: "0 0 6px" }}>{course.title}</h2>
            <p style={{ margin: 0, fontSize: 12, opacity: 0.9 }}>Select a module from the left to view its complete content.</p>
          </div>
          <button style={s.close} onClick={onClose}>×</button>
        </div>
        <div style={s.content}>
          <aside style={s.modules}>
            <h3 style={{ margin: "3px 5px 13px", color: "#075d5d", fontSize: 15 }}>All Modules</h3>
            {course.modules.map((module, i) => {
              const active = activeModule.name === module.name;
              return (
                <button
                  key={i}
                  onClick={() => setActiveModule(module)}
                  style={{ ...s.module, ...(active ? s.activeModule : {}) }}
                >
                  <span style={{ marginRight: 7 }}>{active ? "●" : "○"}</span>
                  {module.name}
                  <span style={{ float: "right" }}>→</span>
                </button>
              );
            })}
          </aside>
          <section style={s.topicContent}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
              <div>
                <div style={{ color: "#bd8b25", fontSize: 10, fontWeight: 900, letterSpacing: 2 }}>
                  MODULE {course.modules.indexOf(activeModule) + 1}
                </div>
                <h2 style={{ fontFamily: "Georgia,serif", color: "#113c43", margin: "4px 0", fontSize: 25 }}>{activeModule.name}</h2>
              </div>
              <div style={{ background: "#eaf5f2", color: "#075d5d", borderRadius: 20, padding: "7px 12px", fontSize: 11, fontWeight: 800 }}>
                {activeModule.topics.length} Topics
              </div>
            </div>
            <p style={{ color: "#718084", fontSize: 12, lineHeight: 1.5, margin: "8px 0" }}>
              Complete topics covered in this module:
            </p>
            <div style={s.topicCards}>
              {activeModule.topics.map((topic, i) => (
                <div key={i} style={s.topicCard}>
                  <div style={{ display: "flex", gap: 9, alignItems: "flex-start" }}>
                    <span style={{ width: 24, height: 24, minWidth: 24, borderRadius: "50%", background: "#075d5d", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 10 }}>
                      {i + 1}
                    </span>
                    <span>{topic}</span>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>
        <div style={s.footer}>
          <button style={{ ...s.btn, flex: 1, minWidth: 180 }} onClick={() => navigate("/contact")}>
            Enquire About This Course →
          </button>
          <button style={{ ...s.btn, flex: 0.4, minWidth: 100, background: "#fff", color: "#075d5d", border: "1px solid #075d5d" }} onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

export default function Courses() {
  const navigate = useNavigate();
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");
  const [level, setLevel] = useState("All");
  const [duration, setDuration] = useState("All");
  const [onlineOnly, setOnlineOnly] = useState(false);
  const [popularOnly, setPopularOnly] = useState(false);
  const [careerOnly, setCareerOnly] = useState(false);
  const [newOnly, setNewOnly] = useState(false);
  const [selectedCourse, setSelectedCourse] = useState(null);

  const filteredCourses = useMemo(() => {
    const text = search.toLowerCase().trim();
    return courses.filter((course) => {
      const searchable = `
        ${course.title}
        ${course.description}
        ${course.category}
        ${course.level}
        ${course.duration}
        ${course.topics.join(" ")}
        ${course.modules.map((m) => `${m.name} ${m.topics.join(" ")}`).join(" ")}
      `.toLowerCase();

      return (
        (!text || searchable.includes(text)) &&
        (category === "All" || course.category === category) &&
        (level === "All" || course.level === level) &&
        (duration === "All" || course.duration === duration) &&
        (!onlineOnly || course.mode === "Online Live") &&
        (!popularOnly || course.badge === "Popular") &&
        (!careerOnly || course.badge === "Career") &&
        (!newOnly || course.badge === "New")
      );
    });
  }, [search, category, level, duration, onlineOnly, popularOnly, careerOnly, newOnly]);

  const clearFilters = () => {
    setSearch("");
    setCategory("All");
    setLevel("All");
    setDuration("All");
    setOnlineOnly(false);
    setPopularOnly(false);
    setCareerOnly(false);
    setNewOnly(false);
  };

  return (
    <>
      <Header />
      <main style={s.page}>
        <section style={s.hero}>
          <div style={s.container}>
            <div style={{ color: "#fff", fontSize: 11, letterSpacing: 3, fontWeight: 800, marginBottom: 12 }}>
              VIGHNAVI ACADEMY • OUR COURSES
            </div>
            <h1 style={s.title}>
              Future-Ready
              <br />
              Skills for a
              <br />
              <span style={s.gold}>Better Tomorrow</span>
            </h1>
            <p style={{ color: "#fff", maxWidth: 600, lineHeight: 1.6, fontSize: 14, marginTop: 18 }}>
              Industry-focused online courses designed to help you learn, build and grow from anywhere in the world.
            </p>
          </div>
        </section>

        <div style={s.container}>
          <div style={s.search}>
            <input
              style={{ ...s.input, flex: "2 1 280px" }}
              placeholder="🔎 Search course, skill, topic, module..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
            <select style={{ ...s.select, flex: "1 1 160px" }} value={category} onChange={(e) => setCategory(e.target.value)}>
              <option value="All">All Categories</option>
              <option value="Programming">Programming</option>
              <option value="Full Stack">Full Stack</option>
              <option value="Data & Analytics">Data & Analytics</option>
              <option value="AI & Emerging Tech">AI & Emerging Tech</option>
              <option value="Cloud & DevOps">Cloud & DevOps</option>
              <option value="Career Preparation">Career Preparation</option>
            </select>
            <select style={{ ...s.select, flex: "1 1 130px" }} value={level} onChange={(e) => setLevel(e.target.value)}>
              <option value="All">All Levels</option>
              <option value="Beginner">Beginner</option>
              <option value="Advanced">Advanced</option>
            </select>
            <select style={{ ...s.select, flex: "1 1 140px" }} value={duration} onChange={(e) => setDuration(e.target.value)}>
              <option value="All">Any Duration</option>
              <option value="3 - 4 Months">3 - 4 Months</option>
              <option value="3 - 5 Months">3 - 5 Months</option>
              <option value="4 - 5 Months">4 - 5 Months</option>
              <option value="4 - 6 Months">4 - 6 Months</option>
              <option value="6 - 8 Months">6 - 8 Months</option>
            </select>
            <button style={{ ...s.btn, width: "auto", padding: "0 18px", background: "#efbe4b", color: "#173d42" }} onClick={clearFilters}>
              Clear
            </button>
          </div>

          <div style={s.filters}>
            <strong style={{ color: "#075d5d", fontSize: 13 }}>Advanced Filters:</strong>
            <label style={s.check}>
              <input type="checkbox" checked={onlineOnly} onChange={(e) => setOnlineOnly(e.target.checked)} />
              Online Live
            </label>
            <label style={s.check}>
              <input type="checkbox" checked={popularOnly} onChange={(e) => setPopularOnly(e.target.checked)} />
              Popular
            </label>
            <label style={s.check}>
              <input type="checkbox" checked={careerOnly} onChange={(e) => setCareerOnly(e.target.checked)} />
              Career Preparation
            </label>
            <label style={s.check}>
              <input type="checkbox" checked={newOnly} onChange={(e) => setNewOnly(e.target.checked)} />
              New Courses
            </label>
          </div>

          <section style={s.section}>
            <div style={{ marginBottom: 25 }}>
              <div style={{ color: "#075d60", fontSize: 11, letterSpacing: 3, fontWeight: 800 }}>EXPLORE OUR COURSES</div>
              <h2 style={{ fontFamily: "Georgia,serif", color: "#103c43", fontSize: "clamp(30px,4vw,43px)", margin: "6px 0" }}>
                Choose Your <span style={{ color: "#bd8b25" }}>Learning Path</span>
              </h2>
              <p style={{ color: "#687b7f", fontSize: 13, margin: 0 }}>
                Showing {filteredCourses.length} of {courses.length} courses
              </p>
            </div>

            {filteredCourses.length ? (
              <div style={s.grid}>
                {filteredCourses.map((course) => (
                  <CourseCard
                    key={course.title}
                    course={course}
                    onModules={setSelectedCourse}
                    onEnquire={() => navigate("/contact")}
                  />
                ))}
              </div>
            ) : (
              <div style={{ textAlign: "center", padding: "60px 20px", border: "1px solid #dce9e7", borderRadius: 15, background: "#f7fbfa" }}>
                <h3 style={{ color: "#075d5d" }}>No Courses Found</h3>
                <p style={{ color: "#718084", fontSize: 13 }}>Try changing your search or filters.</p>
                <button style={{ ...s.btn, width: 150 }} onClick={clearFilters}>Clear Filters</button>
              </div>
            )}
          </section>
        </div>
      </main>
      <Footer />
      {selectedCourse && (
        <CourseModal
          course={selectedCourse}
          navigate={navigate}
          onClose={() => setSelectedCourse(null)}
        />
      )}
    </>
  );
}